/*
 * Copyright ©
 * 2025
 * Osella Ventures, LLC
 * All Rights Reserved
*/

using NeuralNetworkLib;
using SetupLib;

namespace NeuralNetworkExec;

public static class NeuralNetworkRunner
{
    public static double RunNeuralNetwork(NeuralNetworkSetup setup)
    {
        // Create a Neural Network using the structure specified in the Test Setup
        var neuralNetwork = new NeuralNetwork(
            setup.NbrInputs,
            setup.LayerConfigs,
            setup.Rnd,
            setup.UserDefinedFunctions);

        // Train the Neural Network using the training samples generated by the Test Setup
        neuralNetwork.Train(
            setup.Samples.TrainingInputs,
            setup.Samples.TrainingTargets,
            setup.NbrEpochs,
            setup.TrainingRate,
            setup.TrainingMomentum,
            setup.Debug);

        // Test the Neural Network using the testing samples generated by the Test Setup
        neuralNetwork.Test(
            setup.Samples.TestingInputs,
            setup.Samples.TestingTargets,
            setup.Debug);

        // Summarize the Test Results
        setup.UserDefinedFunctions.SummarizeTestResults(setup.Debug);

        return setup.UserDefinedFunctions.ComputeScore();
    }
}
